if(NOT DEFINED EREGION_VERSION_MAJOR)
    SET(EREGION_VERSION_MAJOR 0)
endif()

if(NOT DEFINED EREGION_VERSION_MINOR)
    SET(EREGION_VERSION_MINOR 1)
endif()

if(NOT DEFINED EREGION_VERSION_PATCH)
    SET(EREGION_VERSION_PATCH 0)
endif()

if(NOT DEFINED EREGION_VERSION_SUFFIX)
    SET(EREGION_VERSION_SUFFIX Pre-Alpha)
endif()