name: Example Projecy Linux Build

on:
 push:
   branches: [master]
 pull_request:
   branches: [master]

jobs:
    build-linux:
        name: Linux (Clang)
        runs-on: "ubuntu-latest"
        env:
            CC: clang
            CFLAGS: -Werror
        steps:
            - uses: actions/checkout@v4
            - name: Pull OpenGL Dependencies
              run: |
                sudo apt update
                sudo apt install libglfw3-dev libglm-dev
            - name: Build binary
              run: |
                cd ./example
                cmake .
                make
